image: node:10.15.3

pages:
  script:
    # https://unix.stackexchange.com/questions/83593/copy-specific-file-type-keeping-the-folder-structure
    # https://stackoverflow.com/questions/4210042/how-to-exclude-a-directory-in-find-command
    - >-
      find .
      -type d \( -path ./.vuepress/public -o -path ./public -o -path ./node_modules \) -prune -o
      \( -name '*.sh' -o -name '*.pptx' -o -name '*.docx' -o -name '*.xlsx' \)
      -exec cp --parents \{\} ./.vuepress/public \;
    - yarn install
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master