pipeline {
    agent  {
        node {
            label 'java'
        }
    }
    environment {
        BRANCH = "${BRANCH}"
        M2_HOME = '/usr/lib/maven/apache-maven-3.6.0'
        PATH = "${env.PATH}:${env.M2_HOME}/bin"
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }
    stages {
        stage('Ssh develop Stage') {
            when {
                // environment name: 'BRANCH', value: 'develop'
                branch 'develop'
            }
            steps {
                sh 'ssh user@172.20.249.6 "sh /home/user/test.sh"'
            }
        }
        stage('Ssh master Stage') {
            when {
                branch 'master'
            }
            steps {
                echo 'Ssh master Stage'
            }
        }
    }
}